### ISSUE TITLE
DELAYED_JOB_MAX_RUNTIME does not actually free up workers

### ISSUE THREAD

**Issue by level20peon** [cantino/huginn#1036]
I just was wondering, why my huginn feeds (I emit all incoming events as RSS feeds) have been mostly empty for the last few days.
When I looked into the agents "Last Check" date it says "2 days ago", although I have it scheduled to run ever 5 hours.
So I clicked on "Run" manually and the process started working and output was generated (so this was no DeDuplication issue or something like that).
How can I debug this? Why would an Agent not be run on the schedule I set in the first place? Any pointers?

Update: In fact, all WebSite agents, scheduled to run every 5 hours have their "Last Check" date set to "2 days ago" and all WebSite agents, scheduled to run every 10 minutes have their "Last check" date set to "21h ago".
Also my RSSAgents aren't running on schedule any longer.
Also, my SchedulerAgents haven't ran for 3 days (scheduled to run once a day).

**Comment by jonathanl01** [comment]
@level20peon Are your Website Agent's mode set to "on_change"?  Not sure if it is the cause but it could be.  You can try setting it to "all" or "merge".

**Comment by cantino** [comment]
@level20peon, how are you running Huginn?  It sounds like the scheduler could have crashed.  Do you have logs that you can view?

**Comment by level20peon** [comment]
@jonathanl01 I just set one of the Website Agents to "all" but that didn't change anything. And even if it's set to "on_change" it still should produce a `Last Check` event.

@cantino I use ruby 2.0.0 on a rvm environment and use `bundle exec foreman start` to run huginn. The logs contain nothing that indicates a crash. They at some point just contain the last entry about a worker processing a job and after that just contain info about web requests of RSS output being downloaded from the DataOutputAgent:

    I, [2015-09-19T00:14:13.987221 #21041]  INFO -- : 2015-09-19T00:14:13+0200: [Worker(delayed_job.2 host:host.domain pid:21041)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=399426) COMPLETED after 0.1483
    I, [2015-09-19T00:14:13.988811 #21041]  INFO -- : 2015-09-19T00:14:13+0200: [Worker(delayed_job.2 host:host.domain pid:21041)] 63 jobs processed at 1.7853 j/s, 0 failed
    I, [2015-09-19T00:20:01.098385 #21039]  INFO -- : [41f371d4-5a37-43be-9ea9-cf71d2e36bb3] Started GET "/users/1/web_requests/85/secret_key.xml" for 1.1.1.1 at 2015-09-19 00:20:01 +0200
    I, [2015-09-19T00:20:01.099794 #21039]  INFO -- : [41f371d4-5a37-43be-9ea9-cf71d2e36bb3] Processing by WebRequestsController#handle_request as XML
    I, [2015-09-19T00:20:01.099885 #21039]  INFO -- : [41f371d4-5a37-43be-9ea9-cf71d2e36bb3]   Parameters: {"user_id"=>"1", "agent_id"=>"85", "secret"=>"secret_key"}
    I, [2015-09-19T00:20:01.251088 #21039]  INFO -- : [41f371d4-5a37-43be-9ea9-cf71d2e36bb3]   Rendered text template (0.0ms)
    I, [2015-09-19T00:20:01.251346 #21039]  INFO -- : [41f371d4-5a37-43be-9ea9-cf71d2e36bb3] Completed 200 OK in 151ms (Views: 0.5ms | ActiveRecord: 124.9ms)
    I, [2015-09-19T00:20:04.785433 #21039]  INFO -- : [3a195e05-ffa0-4a24-91ea-9764c0d704e7] Started GET "/users/1/web_requests/46/secret_key.xml" for 1.1.1.1 at 2015-09-19 00:20:04 +0200
    I, [2015-09-19T00:20:04.786636 #21039]  INFO -- : [3a195e05-ffa0-4a24-91ea-9764c0d704e7] Processing by WebRequestsController#handle_request as XML
    I, [2015-09-19T00:20:04.786692 #21039]  INFO -- : [3a195e05-ffa0-4a24-91ea-9764c0d704e7]   Parameters: {"user_id"=>"1", "agent_id"=>"46", "secret"=>"secret_key"}
    I, [2015-09-19T00:20:04.892075 #21039]  INFO -- : [3a195e05-ffa0-4a24-91ea-9764c0d704e7]   Rendered text template (0.0ms)
    I, [2015-09-19T00:20:04.892291 #21039]  INFO -- : [3a195e05-ffa0-4a24-91ea-9764c0d704e7] Completed 200 OK in 106ms (Views: 0.4ms | ActiveRecord: 88.5ms)

**Comment by cantino** [comment]
I would suggest restarting Huginn.  (Control-c and `bundle exec foreman start`.)  You should see lines in the logs that look like `Queuing schedule for every_2m` etc.  If you're not seeing those, the threaded jobs worker probably crashed.  You could scroll back in the logs until you see one of those, then see if there's any error backtrace nearby. (If you're using `less`, jump to the end of the log with `G`, then search backwards with `?Queuing schedule`.)

**Comment by level20peon** [comment]
41963180 rufus-scheduler intercepted an error:{ 41763940 rufus-scheduler intercepted an error:
    13:12:33 jobs.1 | { 41808080 rufus-scheduler intercepted an error:Queuing event propagation{ 72670680 rufus-scheduler intercepted an error:{ 58713200 rufus-scheduler intercepted an error:  41963180   job:{ 58713880 rufus-scheduler intercepted an error:
    13:12:33 jobs.1 | { 54717960 rufus-scheduler intercepted an error:
    13:12:33 jobs.1 | 
    13:12:33 jobs.1 | { 58750040 rufus-scheduler intercepted an error:  54717960   job:
    13:12:33 jobs.1 | 
    13:12:33 jobs.1 |   72670680   job:
    13:12:33 jobs.1 |   72670680     Rufus::Scheduler::EveryJob "5m" {}
    13:12:33 jobs.1 |   72670680   error:
    13:12:33 jobs.1 |   72670680     72670680
    13:12:33 jobs.1 |   72670680     ActiveRecord::ConnectionTimeoutError
    13:12:33 jobs.1 |   72670680     could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
    13:12:33 jobs.1 |   58713200   job:
    13:12:33 jobs.1 | 
    13:12:33 jobs.1 |   58713200     Rufus::Scheduler::EveryJob "1m" {}
    13:12:33 jobs.1 | 
    13:12:33 jobs.1 | 
    13:12:33 jobs.1 |   41963180     Rufus::Scheduler::CronJob "0 13 * * * Europe/Berlin" {}
    13:12:33 jobs.1 | 
    13:12:33 jobs.1 |   41963180   error:
    13:12:33 jobs.1 |   41963180     41963180  41763940   job:
    13:12:33 jobs.1 |   41963180     ActiveRecord::ConnectionTimeoutError
    13:12:33 jobs.1 |   41963180     could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
    13:12:33 jobs.1 |   41963180       /home/foo/.rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'

I have a lot of Agents set up so I suppose that my setup needs more resources than one with just a couple of dozen Agents. What I don't understand is that all of those jobs are suppsed to be ran in sequence and not in parallel. I got 2 Workers and might be browsing the webinterface and my RSS reader is pulling the feeds (one after another, that is) from the OutputAgents at the same time. That should result in 4 database connections tops. The default pool is set to 10 concurrent database connections, so I don't get why the system could possibly run out of resources here. I set the pool to 20 now and will see if that does the trick.

**Comment by level20peon** [comment]
ok, setting the pool to 20 didn't do the trick. However, I commented out that `#dj2: bundle exec script/delayed_job -i 2 run` in the `Procfile` and launched a second worker by calling `bundle exec rake jobs:work` instead. It ran for half a day without crashing now (it usually crashed within 1-2 hours before). Any pointers on what could cause that behaviour?

**Comment by cantino** [comment]
Very interesting.  I'd expect having a larger DATABASE_POOL would fix this.  @dsander, sorry to bug you, but any ideas on this?

**Comment by level20peon** [comment]
I am using this version btw: https://github.com/cantino/huginn/commit/065a35c02421bc19a24737c7d586ecc6298e21e4

**Comment by dsander** [comment]
@level20peon I guess you tried a never version of huginn judging by your comment on 06b022f161aae5b8a107fb962c0cf0c62149a8d3 ?

What kind of `Procfile` are you running right now? I would recommend just using the basic version first (web + threaded worker) and then try the "old" setup with seperated background workers (web + schedule + twitter + one DJ worker) to see if one of the setups performs better.

**Comment by level20peon** [comment]
This is my `Procfile` that leads to the crashes:

    web: bundle exec unicorn -c config/unicorn.rb
    jobs: bundle exec rails runner bin/threaded.rb
    dj2: bundle exec script/delayed_job -i 2 run

If I just use this as `Procfile` I don't get crashes:

    web: bundle exec unicorn -c config/unicorn.rb
    jobs: bundle exec rails runner bin/threaded.rb
    dj2: bundle exec rake jobs:work

**Comment by dsander** [comment]
That is odd, I don't see how the second DJ worker could have an effect on the scheduler. Can you try to run the "old" example of the Procfile?
```
web: bundle exec unicorn -c config/unicorn.rb
schedule: bundle exec rails runner bin/schedule.rb
twitter: bundle exec rails runner bin/twitter_stream.rb
dj: bundle exec script/delayed_job run
```

**Comment by level20peon** [comment]
I updated to https://github.com/cantino/huginn/commit/06b022f161aae5b8a107fb962c0cf0c62149a8d3 and tested the following configurations with the following results. "not working" means the scheduler at some point just won't run any more agents (there are no "Queuing" log entries any longer), alas there's no crash visible in the logs any longer, after updating. It just stops working. The syslog also doesn't contain anything about those processes.

I am running Huginn with `bundle exec foreman start > ~/huginn_stdout.log 2> ~/huginn_stderr.log`. "huginn_stderr.log" is always empty btw, no idea if this should be the case or not, I just thought this would help tracking down any issues.


working:
    web: bundle exec unicorn -c config/unicorn.rb
    jobs: bundle exec rails runner bin/threaded.rb
    dj: bundle exec rake jobs:work

working:
    web: bundle exec unicorn -c config/unicorn.rb
    jobs: bundle exec rails runner bin/threaded.rb
    dj: bundle exec script/delayed_job run

not working:
    web: bundle exec unicorn -c config/unicorn.rb
    jobs: bundle exec rails runner bin/threaded.rb
    dj: bundle exec script/delayed_job -i 2 run

not working:
    web: bundle exec unicorn -c config/unicorn.rb
    schedule: bundle exec rails runner bin/schedule.rb
    twitter: bundle exec rails runner bin/twitter_stream.rb
    dj: bundle exec script/delayed_job run

**Comment by cantino** [comment]
Any chance you're running out of RAM?

**Comment by level20peon** [comment]
No, I have plenty of free RAM on the machine this runs on.

**Comment by cantino** [comment]
I'm surprised you saw a difference between

```
web: bundle exec unicorn -c config/unicorn.rb
jobs: bundle exec rails runner bin/threaded.rb
dj: bundle exec script/delayed_job run
```

and 

```
web: bundle exec unicorn -c config/unicorn.rb
jobs: bundle exec rails runner bin/threaded.rb
dj: bundle exec script/delayed_job -i 2 run
```

Which error did you get?

**Comment by level20peon** [comment]
Well, I am still testing various permutations of those entries and haven't yet come to a conclusion. The way it looks right now is that no configuration works forever. After a few days, eventually every configuration breaks.
There are no specific errors, it just stops working: no more events are being generated. The webinterface still works, but no jobs are being processed any longer.

The last few lines in the console output look like this: http://pastebin.com/wGCNtypE
(There's nothing in particular at all inside the `production.log`, `unicorn.log` or the syslog)

Seems like there are some errors, but I cannot decipher them. Is there any way to increase verbosity?

**Comment by cantino** [comment]
@dsander, I wonder if this is related to the issues I'm having?

**Comment by dsander** [comment]
@cantino The last log @level20peon posted sure looks like it. Even though I have no idea how everything would just stop working without throwing an exception.

**Comment by level20peon** [comment]
So how can we track this down?

**Comment by cantino** [comment]
I'll try to add some more monitoring this weekend and see if I can
reproduce.  The challenge is that it takes so many days before it happens
for me.  How quickly does it happen for you?

@dsander, do we have our threads set to abort on exception?

**Comment by level20peon** [comment]
It takes a few days until this happens for me, but totally random on the amount: it's like anything between one and five days.

**Comment by cantino** [comment]
@dsander, I saw one of these in the logs:

```
112042590 rufus-scheduler intercepted an error:
  112042590   job:
  112042590     Rufus::Scheduler::EveryJob 60 {}
  112042590   error:
  112042590     112042590
  112042590     ActiveRecord::StatementInvalid
  112042590     Mysql2::Error: This connection is in use by: #<Thread:0x1175d3c8 sleep>: SHOW TABLES 
  112042590       /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb
:305:in `query'
  112042590       /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb
:305:in `block in execute'
  112042590       /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:473:i
n `block in log'
  112042590       /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instru
ment'
  112042590       /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:467:i
```

**Comment by dsander** [comment]
@cantino I have 15 threads running, one additional would make sense for my JabberAgent but I don't know what the other one is doing.

**Comment by cantino** [comment]
Have any ideas on the `This connection is in use by` error?

**Comment by cantino** [comment]
Also, I noticed that a floating bin/threaded was present, killed it, restarted everything, and now it looks like this:

<img width="968" alt="screen shot 2015-10-04 at 12 16 57 pm" src="https://cloud.githubusercontent.com/assets/83835/10269630/0290a58e-6a92-11e5-97e4-9845ee22048e.png">

**Comment by dsander** [comment]
@cantino Maybe we are missing a mutex or a `with_connection` block somewhere, does the backtrace list our code somewhere?

**Comment by cantino** [comment]
```
ActiveRecord::StatementInvalid: Mysql2::Error: This connection is in use by: #<Thread:0x1175d3c8 sleep>: SELECT  `agents`.* FROM `agents` WHERE `agents`.`id` = 12 LIMIT 
1
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `exec_query'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_st
atements.rb:351:in `select'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/querying.rb:39:in `find_by_sql'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation.rb:639:in `exec_queries'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation.rb:515:in `load'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation.rb:243:in `to_a'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/finder_methods.rb:475:in `find_take'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/finder_methods.rb:105:in `take'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/finder_methods.rb:442:in `find_one'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/finder_methods.rb:423:in `find_with_ids'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/relation/finder_methods.rb:71:in `find'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/querying.rb:3:in `find'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/core.rb:131:in `find'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:84:in `process_tweet'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:240:in `block (3 levels) in handle_status'
        /home/huginn/app/releases/20151001032735/lib/agent_runner.rb:62:in `block in with_connection'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
        /home/huginn/app/releases/20151001032735/lib/agent_runner.rb:61:in `with_connection'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:239:in `block (2 levels) in handle_status'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:237:in `each'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:237:in `block in handle_status'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:235:in `each'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:235:in `handle_status'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:171:in `block (2 levels) in run'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:198:in `call'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:198:in `block in stream!'
        /home/huginn/app/shared/bundle/ruby/2.1.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:296:in `call'
        /home/huginn/app/shared/bundle/ruby/2.1.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:296:in `parse_stream_line'
        /home/huginn/app/shared/bundle/ruby/2.1.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:227:in `block in receive_stream_data'
        /home/huginn/app/shared/bundle/ruby/2.1.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:226:in `each'
        /home/huginn/app/shared/bundle/ruby/2.1.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:226:in `receive_stream_data'
        /home/huginn/app/shared/bundle/ruby/2.1.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:128:in `call'
        /home/huginn/app/shared/bundle/ruby/2.1.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:128:in `<<'
        /home/huginn/app/shared/bundle/ruby/2.1.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:128:in `receive_data'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
        /home/huginn/app/shared/bundle/ruby/2.1.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
        /home/huginn/app/releases/20151001032735/app/models/agents/twitter_stream_agent.rb:169:in `run'
        /home/huginn/app/releases/20151001032735/app/concerns/long_runnable.rb:69:in `block in run!'
```

**Comment by cantino** [comment]
So maybe `stream.each_item` needs something around it?

**Comment by dsander** [comment]
It [has](https://github.com/cantino/huginn/blob/master/app/models/agents/twitter_stream_agent.rb#L239-L241), I wonder if we could use `rbtrace` to attach to the running process and get information about the thread that does did not release the connection.

What's strange is that [AR::ConnectionPool](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html) claims to be thread safe and not return a connection that is currently used by a different thread.

**Comment by cantino** [comment]
We're using a combination of EventMachine and Threads, right?  Maybe that's introducing a race condition?

(As an aside, it looks like Rails won't be running the Reaper by default: https://github.com/rails/rails/issues/9907)

**Comment by dsander** [comment]
@cantino I pushed two new branches which might solve the problem ([ensure-connection-checkout](https://github.com/cantino/huginn/compare/cantino:master...dsander:ensure-connection-checkout?expand=1)), or at least help debug it ([rbtrace](https://github.com/cantino/huginn/compare/cantino:master...dsander:rbtrace?expand=1))

rbtrace is pretty awesome, its basically [strace for ruby](https://github.com/tmm1/rbtrace)

**Comment by cantino** [comment]
Awesome, I'll try merging those into my deploy branch.

**Comment by level20peon** [comment]
I integrated the changes introduced here: https://github.com/cantino/huginn/compare/cantino:master...dsander:ensure-connection-checkout?expand=1

However, huginn still crashes. You can find a log of the last ~12 hours here (contains only debug info): http://pastebin.com/NsUbEGEL

**Comment by level20peon** [comment]
... and another one: http://pastebin.com/CzR08G53

**Comment by dsander** [comment]
@level20peon Do you have the actual exception somewhere in your logs? All I am seeing is the backtrace. It should look somewhat like the first line of the exception @cantino posted.

**Comment by level20peon** [comment]
I have that first full log at home and will look if I find any error line in there as soon as I get home. Here's a new log (Huginn stopped working twice already today) including errors: http://pastebin.com/YjfiVYLv

**Comment by level20peon** [comment]
Apart from the errors visible in that log I last posted I also got the following ones:

    10:12:25 dj.1       | Agent#81: Error when fetching url: Mysql2::Error: MySQL server has gone away: ROLLBACK

and

    18:09:37 dj2.1      | Agent#9: Error when fetching url: Failed: #<Faraday::Response:0x00000006299ea0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="... <- the whole body is logged

But Huginn seems to have continued for hours after those errors before stopping to process any further events.

**Comment by level20peon** [comment]
Next log: http://pastebin.com/xNWkrf79

**Comment by dsander** [comment]
Did you restart huginn in between the logs you posted? 

` Mysql2::Error: MySQL server has gone away`

I think that mostly happens when a either dies or drops the connection because a query took too long, do you have agents which store large events?

`Agent#9: Error when fetching url: Failed: #`
That looks normal, fetching an url can fail from time to time.

`Agent#9: Error when fetching url: execution expired (Delayed::Worker.max_run_time is only 300 seconds)`
That also just looks like a slow website.

Can you try to remove the threaded worker and run all the background processes seperately?

```
web: bundle exec unicorn -c config/unicorn.rb
schedule: bundle exec rails runner bin/schedule.rb
twitter: bundle exec rails runner bin/twitter_stream.rb
dj: bundle exec script/delayed_job run
dj2: bundle exec script/delayed_job -i 2 run
````

**Comment by level20peon** [comment]
Yes, I had to restart because Huginn stops processing schedules at some point.

Yes, I do have agents which store large events. I use WebsiteAgents to grab full html pages which then are processed further by EventFormattingAgents (because parsing within the WebsiteAgents is only possible to a certain degree).

OK @ the fetching url errors.

I will run Huginn with the setup you proposed and see what happens. btw: is it ok if I leave that twitter line commented? I don't see the point of running an extra process for something I never use.

**Comment by level20peon** [comment]
It stopped working despite using the proposed configuration: http://pastebin.com/MjrgJX3L

**Comment by cantino** [comment]
Could you show the line above the top line of that backtrace too?  That would have the actual error message.  (Above `~/huginn/app/models/agents/website_agent.rb:269:in `check_url'`)

**Comment by level20peon** [comment]
The thing is that I pipe Huginn's output into a log file. Before I post it on pastebin I remove all lines except the backtrace lines, since they are not important for debugging (mostly, that is). Since dsander stated that the few "errors" I got in my log are irrelevant (see this post: https://github.com/cantino/huginn/issues/1036#issuecomment-146303146) I didn't include them in that last log. There were no errors other than the ones deemed irrelevant.

I will include them in the next log I post again if you like, since I already got rid of that old log.

It would also help if you could tell me what exactly I can provide to help debug this, since I am out of ideas... I just see Huginn stopping to work every day, which I would like to solve asap. I put over a week of work into migrating everything I had on yahoo pipes into this system, without success so far as it seems, so I will do whatever it takes to help solve this issue.

**Comment by cantino** [comment]
I appreciate your patience @level20peon, I'm having similar issues.  Something has changed in the system that is breaking things, and we're trying to figure out what it is.

If you can provide the few lines above those traces, that would be helpful, but you could also pause for a few days and let us see if we can figure this out on my system, which is also failing.

**Comment by level20peon** [comment]
ok, I got a new log which might provide some insight (I cleaned it up a little and annotated 4 errors, resulting from 2 different agents): http://pastebin.com/tVhnf849

As you can see, all 4 errors result from WebsiteAgents which use an array of urls... maybe that's the cause? In all cases one of the two websites inside that array (both agents hold 2 websites per array) works, while the other one times out.

However, that might of course just be a coincidence!?

**Comment by dsander** [comment]
@level20peon The backtraces may look scary but seem totally normal to me,
`12:17:20 dj2.1      | Agent#9: Error when fetching url: execution expired (Delayed::Worker.max_run_time is only 300 seconds)` just means the website did no respond within 300 seconds, you could try to increase `DELAYED_JOB_MAX_RUNTIME` in your `.env` file but I doubt the you will get a response withint 10 minutes when 5 were not enough :smile: 

If you have multiple Agents that take a really long time to run it might even explain that your agents do not seem to run on shedule. Each delayed_job process can just run one agent at a time, if you have two workers and two Agents running for 5 minutes, no other Agent will run until the first two time out after 5 minutes.

When you notice a your agents stalling again, check the "Account" -> "Job Management" page, my guess is that you should see a bunch of jobs queuing up.

**Comment by level20peon** [comment]
I realize that those events might block jobs for a certain period of time, however those blocking agents aren't actually killed after 5 minutes. Right now I have agents with the "status" `running` and "created" `~2h ago for admin` in the job management page, which either means that the agent is still actually running after 2 hours instead of being killed after the set timeout (5 minutes) or the scheduler just crashed and didn't schedule anything afterwards, so this agent's last status (running) was still displayed, because it just wasn't updated any longer.

**Comment by dsander** [comment]
No I don't think there is a way to kill a job manually once they are handled by delayed_job

Did the status of the jobs change after a few minutes? I tested the multiple delayed_job worker setup myself and I had some issues with duplicated events, so it might be that the second worker is not picking up new jobs properly.

However if the scheduler did not crash you should see new events scheduled, if it did crash there should be something in the scheduler log (the location may depend on the way you run huginn, if you use runit it should be in `/home/huginn/huginn/log/schedule-1/current`)

**Comment by level20peon** [comment]
The status doesn't change even after hours. Maybe this in fact is the problem in my Huginn instance after all (I didn't check the job page before, just was scanning the logs). So the problem right now is that the workers / jobs aren't killed after the timeout I set in `.env`, even though the log says so.

What about those duplicates? I read a thread about other people having such isssues, but it stopped being updated after a while.

**Comment by dsander** [comment]
I did some tests with agents timing out and everything went well. One Agent was still shown as running in the management page once after the delayed job worker did not shut down properly, however after I restarted them the job was re enqueued. Keep in mind the failed/timed-out jobs will be re enqueued a few times before they show up as failed.

If new events are created I think you installation may just work fine, the backlogs a saw were all just about agents timing out.



> What about those duplicates? I read a thread about other people having such isssues, but it stopped being updated after a while.

I had some in my production instance but did not debug further since I normally just run one DJ worker. Locally the different DJ workers are properly locking the jobs using their PIDs, so there is no way the multiple workers were causing the issue I saw.

**Comment by level20peon** [comment]
> I did some tests with agents timing out and everything went well. One Agent was still shown as running in the management page once after the delayed job worker did not shut down properly, however after I restarted them the job was re enqueued. Keep in mind the failed/timed-out jobs will be re enqueued a few times before they show up as failed.

After doing some more tests, that seems to be my problem; Agents are shown as "running" for hours (my timeout for them is set to 3 minutes), with "Attempts" being "0", so they did not properly shut down like they should. Since I use 2 worker threads, the system continues to process jobs for a while if one worker gets "congested", but the second worker will get congested, too after some time, so the whole job queue just keeps growing and growing.
Restarting the Huginn system re-enqueued those jobs just fine, but I can't just sit watching at a console window all day waiting for the workers to get congested in order to restart Huginn every time. The amounts of jobs that are produced in my setup is large enough to make Huginn stop working at least once or twice a day.
I could of course write a script to restart Huginn every hour, but I don't think this would be an elegant solution given the fact that the workers should timeout and be killed like they are supposed to, don't you think?

**Comment by dsander** [comment]
You now don't get the `execution expired` exceptions anymore, or does it throw the exception but just not terminate the job?

The next time you have stuck jobs can you check if the job is locked by a PID that is still running? 

`bundle exec rails runner "pp Delayed::Job.select(:id, :run_at, :locked_at, :failed_at, :locked_by, :queue, :created_at).all"`

The command needs to be run as your huginn user in the huginn root directory.

**Comment by level20peon** [comment]
It throws the exception but does not terminate the job.

I just ran that command and got outputs like the following... but I don't really know how to make sense of them / what to do now exactly:

     #<Delayed::Backend::ActiveRecord::Job:0x00000007f98560
      id: 414020,
      run_at: Sun, 18 Oct 2015 12:07:46 CEST +02:00,
      locked_at: nil,
      failed_at: nil,
      locked_by: nil,
      queue: nil,
      created_at: Sun, 18 Oct 2015 12:07:46 CEST +02:00>,
     #<Delayed::Backend::ActiveRecord::Job:0x00000007f983d0
      id: 414021,
      run_at: Sun, 18 Oct 2015 12:07:46 CEST +02:00,
      locked_at: nil,
      failed_at: nil,
      locked_by: nil,
      queue: nil,
      created_at: Sun, 18 Oct 2015 12:07:46 CEST +02:00>,
     #<Delayed::Backend::ActiveRecord::Job:0x00000007f981f0
      id: 414022,
      run_at: Sun, 18 Oct 2015 12:07:46 CEST +02:00,
      locked_at: nil,
      failed_at: nil,
      locked_by: nil,
      queue: nil,
      created_at: Sun, 18 Oct 2015 12:07:46 CEST +02:00>]

**Comment by level20peon** [comment]
I did a `bundle update` yesterday and had no "congestion" since then. I don't think this is a coincidence since the congestion occured at least 2-3 times a day before. Here are the gems that got updated... could you check your version and tell me if you have the problems I describe in this thread with the pre-update versions (the ones on the left) ? Interestingly enough, I updated them just 14 days ago, so I think it's improbable that you all have versions which are from beyond that time.

    capistrano-rails-1.1.3 -> capistrano-rails-1.1.5
    faraday-0.9.1 -> faraday-0.9.2
    guard-livereload-2.4.0 -> guard-livereload-2.5.0
    libv8-3.16.14.11-x86_64-linux -> libv8-3.16.14.13-x86_64-linux
    mini_magick-4.3.5 -> mini_magick-4.3.6
    pry-0.10.2 -> pry-0.10.3
    sass-3.4.18 -> sass-3.4.19

**Comment by cantino** [comment]
Fascinating.  You did a git pull, or an actual `bundle update` without specifying a specific gem?

**Comment by level20peon** [comment]
I did a `bundle update` without specifying a specific gem.

**Comment by cantino** [comment]
None of those look like they'd do it.  Did any other gems change?

**Comment by level20peon** [comment]
None that I can see.

**Comment by cantino** [comment]
Were you using any JavaScriptAgents?

**Comment by level20peon** [comment]
No, I honestly thought that faraday was the culprit though. However, I am using:

    Agents::ChangeDetectorAgent
    Agents::DataOutputAgent
    Agents::DeDuplicationAgent
    Agents::DelayAgent
    Agents::EmailAgent
    Agents::EventFormattingAgent
    Agents::RssAgent
    Agents::SchedulerAgent
    Agents::TriggerAgent
    Agents::WebsiteAgent

I also noticed that you renamed the BufferAgent to DelayAgent. I had a test scenario set up before you did which used this agent... maybe it was something related to conflicting naming conventions?

**Comment by cantino** [comment]
Perhaps it was the rename.

Is this issue closeable?

**Comment by level20peon** [comment]
I think this requires some days of monitoring, but I will close it (preliminary) anyways.
