### ISSUE TITLE
Can't specify a percent-encoded `/` in WebsiteAgent URLs

### ISSUE THREAD

**Issue by strugee** [cantino/huginn#1735]
I'm trying to scrape something through [fulldom-server](https://github.com/strugee/fulldom-server) which involves sending percent-encoded `/`s in the URL. I can't make this work with the WebsiteAgent, because whenever I include a `%2F`, it gets escaped to `%252F` (i.e. the `%` is replaced with `%25`).

Possibly related to #1534?

**Comment by dsander** [comment]
Try not percent encoding the slashes, the encoding is done automatically:

```
{
  "expected_update_period_in_days": "2",
  "url": "http://requestb.in/rc5j2urc?url=http://www.google.com",
  "type": "html",
  "mode": "on_change"
}
```
<img width="880" alt="screenshot 2016-10-15 11 35 22" src="https://cloud.githubusercontent.com/assets/20943/19409025/803ac49e-92cb-11e6-93cb-1d5f2dc0f1ba.png">

**Comment by strugee** [comment]
@dsander the problem here is that the slashes are not part of the querystring, so theyre not escaped. Instead, they're treated as path component separators.

**Comment by dsander** [comment]
I see, not sure if that will work. I tried `http://localhost:1337/http://www.xkcd.com?selector=body` with curl and express does not seem to like requests like this either.
Changing the API to something like `?url=<url>&selector=<selector>` would probably be the easiest solution as it does not require any manual encoding of special characters.

**Comment by strugee** [comment]
@dsander if it's non-trivial to fix I can change the API... but I'd prefer to fix this in Huginn. Seems like a shortcoming that will come up again at some point.

**Comment by dsander** [comment]
Played with it a little more and it seems to be working like this:
```
{
  "expected_update_period_in_days": "2",
  "url": "http://localhost:1337/http:%2F%2Fwww.xkcd.com?selector=body",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "#comic img",
      "value": "@src"
    },
    "title": {
      "css": "#comic img",
      "value": "@alt"
    },
    "hovertext": {
      "css": "#comic img",
      "value": "@title"
    }
  }
}
```
Allowing to set the URL in the query string would in my optionin still be nicer because manual encoding isn't required:
```
{
  "expected_update_period_in_days": "2",
  "url": "http://localhost:1337?selector=body&url=http://xkcd.com",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "#comic img",
      "value": "@src"
    },
    "title": {
      "css": "#comic img",
      "value": "@alt"
    },
    "hovertext": {
      "css": "#comic img",
      "value": "@title"
    }
  }
}
```

**Comment by strugee** [comment]
@dsander one reason I don't want to put it in the querystring is because I'm not 100% confident Huginn can handle all the edge cases. For example: what if you specify a URL which itself takes a querystring?

I also can't reproduce your solution: I still get `Fetching http://localhost:3528/https:%252F%252F...` in the logs. I'll try updating Huginn and see if it's still there.

**Comment by dsander** [comment]
I don't know about all edge cases, but normal URLs with query strings seem to work well:
```
{
  "expected_update_period_in_days": "2",
  "url": "http://requestb.in/sx2g7csx?selector=body&url=http://xkcd.com?test=test",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "#comic img",
      "value": "@src"
    }
  }
}
```
<img width="903" alt="screenshot 2016-10-16 11 20 12" src="https://cloud.githubusercontent.com/assets/20943/19416508/c1fa3ff0-9392-11e6-9f89-11cfd03fbc08.png">

**Comment by strugee** [comment]
^^^ FYI pushed this out last night.

**Comment by dsander** [comment]
Nice, is that change working well with the WebsiteAgent?

**Comment by strugee** [comment]
Yeah, seems to be working OK.

**Comment by dsander** [comment]
Can we close the issue? I think specifying an URL as part of the URL is a pretty uncommon use case (at least we did not get any other issues reported about encoding slashes).

**Comment by strugee** [comment]
I suppose... although I still think it would be better if we fixed this. Your call though.

**Comment by dsander** [comment]
@knu Do you know if that something we can fix (easily)?

**Comment by knu** [comment]
I still don't see how "%2F" could get escaped to "%252F".  Is there any sample WebsiteAgent configuration or even a URL I can try?

**Comment by dsander** [comment]
@knu Sorry now I remember it was working for me as well, @strugee did updating Huginn fix the issue for you?

**Comment by strugee** [comment]
@dsander I forgot to upgrade my Huginn, so I'm not sure if it's fixed.

I'll let you know ASAP but it may take a little bit of time because support for Ruby 2.1 (the Ruby Debian ships) got dropped, so I have to set up RVM, upgrade, etc. :(

**Comment by cantino** [comment]
Is this working for you now?

**Comment by strugee** [comment]
Seems to be working! So sorry for the delay.

I didn't test super thoroughly though so if it reappears, I'll reopen. Cheers :)
